const template = {
    "Description": "This is a test item generated by CI"
  , "PrimaryCategory": {"CategoryID": "377"}
  , "StartPrice": "1.0"
  , "CategoryMappingAllowed": "true"
  , "Country": "US"
  , "ConditionID": "3000"
  , "Currency": "USD"
  , "DispatchTimeMax": "3"
  , "ListingDuration": "Days_7"
  , "PaymentMethods": "PayPal"
  , "PayPalEmailAddress": "travis@longridgetraders.com"
  , "PictureDetails": {"PictureURL": "http://i1.sandbox.ebayimg.com/03/i/00/30/07/20_1.JPG?set_id=8800005007"}
  , "PostalCode": "95125"
  , "Quantity": "1"
  , "ReturnPolicy": {
      "ReturnsAcceptedOption": "ReturnsAccepted"
      , "RefundOption": "MoneyBack"
      , "ReturnsWithinOption": "Days_30"
      , "Description": "If you are not satisfied, return the book for refund."
      , "ShippingCostPaidByOption": "Buyer"
  }
  , "ShippingDetails": {
      "ShippingType": "Flat"
      , "ShippingServiceOptions": {
          "ShippingServicePriority": "1"
          , "ShippingService": "USPSMedia"
          , "ShippingServiceCost": "2.50"
      }
  }
}

export function Item () {
  return Object.assign(template, {
    Title: `CI - Test Item${Math.floor(Math.random() * Date.now())}`
  })
}